read and write in send (fixes #1)
sajattack/bitbang-hal pull request #2
Opened 2019-05-12 00:14 UTC by sajattack

@austinglaser Please review. Is this a correct implementation now?

2019-05-13 17:00 UTC, austinglaser requested changes
Also, I haven't tested these changes on hardware

2019-05-13 17:00 UTC, austinglaser commented on src/spi.rs
> +    read_val: u8,
Seems to me that `read_val` should be `Option<u8>`, so that `read()` can return an error if it's called when no data is available. Then `read()` can be

```Rust
fn read(&mut self) -> nb::Result<u8, Error> {
    if let Some(byte) = self.read_val.take() {
        Ok(byte)
    } else {
        Err(Something)
    }
}
```

But I also don't think this is strictly required by the `embedded-hal` trait, it's just a way to help catch invalid uses of your interface.

2019-05-13 17:00 UTC, austinglaser commented on src/spi.rs
> +            }
I'm not sure this code is correct in the case where `self.mode.phase == CaptureOnSecondTransition`. In that case in the original implementation, you have a clock transition before reading the first bit. Here, you immediately read the pin on entry, which may be in an indeterminate state depending on the peripheral to which you're interfacing.

2019-05-13 17:25 UTC, austinglaser commented on src/spi.rs
> +            }
I think I may be wrong about something here -- I'll try to prove/disprove this problem, and get back to you

2019-05-13 17:29 UTC, austinglaser commented on src/spi.rs
> +            }
Nope, that is correct. Sorry for the confusin

2019-05-14 00:35 UTC, sajattack commented
@austinglaser Try now.

2019-05-14 01:05 UTC, austinglaser commented
LGTM, at least as far as I can tell without actually testing on hardware

2019-05-14 01:09 UTC, merged